INSERT INTO regions (code, name) VALUES
    ('AF',	'Ahafo'),
    ('AH',	'Ashanti'),
    ('BO',	'Bono'),
    ('BE',	'Bono East'),
    ('CP',	'Central'),
    ('EP',	'Eastern'),
    ('AA',	'Greater Accra'),
    ('NE',	'North East'),
    ('NP',	'Northern'),
    ('OT',	'Oti'),
    ('SV',	'Savannah'),
    ('UE',	'Upper East'),
    ('UW',	'Upper West'),
    ('TV',	'Volta'),
    ('WP',	'Western'),
    ('WN',	'Western North');